version: '3'
services:
  web:
    image: nginx:latest
    ports:
      - 8080:8080
  db:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=mysecretpassword
    volumes:
      - db_data:/var/lib/mysql
volumes:
  db_data:
